apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-login-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: flask-login
  template:
    metadata:
      labels:
        app: flask-login
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: flask-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: flask-node
                    operator: In
                    values:
                      - enabled
      imagePullSecrets:
      - name: ecr-secret
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: flask-app
        image: 211125325699.dkr.ecr.us-east-1.amazonaws.com/flask-app:v5
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets
        livenessProbe:
          httpGet:
            path: /login
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /login
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/flask
      - name: sidecar-logger
        image: busybox
        command: ["sh", "-c", "tail -n+1 -F /var/log/flask/app.log"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/flask
      volumes:
      - name: log-volume
        emptyDir: {}