apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flask-app-pdb
  namespace: flask-app
  labels:
    app: flask-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: flask-app