apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
  namespace: app
---
# flask-sa-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-role
  namespace: app
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "serviceaccounts", "services", "endpoints"]
    verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-rolebinding
  namespace: app
subjects:
- kind: ServiceAccount
  name: flask-sa
  namespace: app
roleRef:
  kind: Role
  name: flask-role
  apiGroup: rbac.authorization.k8s.io