version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
    - 3306:3306
    volumes:
    - mysql_data:/var/lib/mysql
  flask-app:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy
    container_name: flask-login-app
    restart: always
    ports:
    - 5000:5000
    environment:
      DB_HOST: mysql
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
    depends_on:
    - mysql
volumes:
  mysql_data: {}